CPPFLAGS= -Wall -Wextra -pedantic -g

all:
	# Insert command to compile the code and generate executable
	g++ -std=c++17 -fmax-errors=1 $(CPPFLAGS) Array.hpp
	g++ -std=c++17 -fmax-errors=1 $(CPPFLAGS) Test_Array.cpp -o test
run:
	# Insert command to run the executable
	./test
checkmem:
	# Insert command to run the executable with valgrind

clean:
	# Insert command to clean object files, executables
