CPPFLAGS= -Wall -Wextra -pedantic -g

all:
	# Insert command to compile the code and generate executable

run:
	# Insert command to run the executable

checkmem:
	# Insert command to run the executable with valgrind

clean:
	# Insert command to clean object files, executables
